language: php

php:
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true

install:
    - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-progress"
    - composer install $flags

script:
    - ./bin/phpunit --testdox