language: php

php:
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true

before_install:
    - composer selfupdate

script:
    - ./vendor/bin/phpunit --testdox